# Site Settings
title: Thiago Rossener | Desenvolvedor Web
email: thiago@rossener.com
description: Um blog sobre desenvolvimento web e melhoramento pessoal.
baseurl: ""
url: "http://www.rossener.com"

# User Settings
username: Thiago Rossener
user_description: Desenvolvedor web, apaixonado por desafios, tecnologia, pessoas e melhoramento pessoal.
twitter_username: thiagorossener
github_username: thiagorossener
disqus_username: rossener

# Build settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-redirect-from
