# Site Settings
title: Thiago Rossener | Desenvolvedor Full Stack
email: thiago@rossener.com
description: Um blog sobre desenvolvimento web e melhoramento pessoal.
baseurl: ""
url: "https://www.rossener.com"
google_analytics: "UA-99616615-1"

# User Settings
username: Thiago Rossener
user_description: Desenvolvedor full stack, apaixonado por desafios, tecnologia, pessoas & melhoramento pessoal.
github_username: thiagorossener
facebook_username: thiagorossener
twitter_username: thiagorossener
instagram_username: thiagorossener
linkedin_username: thiagorossener
medium_username: thiagorossener
disqus_username: rossener

# Build settings
markdown: kramdown
permalink: /:title/

# Plugins
gems:
  - jekyll-redirect-from

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Portf√≥lio
    url: /portfolio/
  - title: Sobre mim
    url: /sobre-mim/
  - title: Contato
    url: /contato/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
