# Site Settings
title: Eduardo Augusto Benigno da Silva | Back-End Developer
email: eaugusto@outlook.com
description: Come with me in a fantastic travel to Technology World!
baseurl: ""
url: "http://eaugusto.com"
google_analytics: "UA-119586029-1"

# User Settings
username: Eduardo Augusto Benigno da Silva
user_description: Java Developer with passion for excellence and sharing!
github_username: eaugusto
facebook_username: eaugustosilva
twitter_username: mreaugusto
instagram_username: 
linkedin_username: mreaugusto
medium_username: mreaugusto
disqus_username: eaugusto

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jekyll-redirect-from
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio/
  - title: About me
    url: /about-me/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
